### PR TITLE
feat: add overlay tappable for geometry renderder

### LINKED ISSUE #375: Geometry renderer tappable
**Is your feature request related to a problem? Please describe.**
I have been making map for ios, and my work requires tapping on the geojson layer parsed and rendered by google-maps-ios-utils. 

 **Describe the solution you'd like**
My solution is setting the tappable of the rendered geometries to true, so that when I the method `didTapOverlay()` is triggered when I tap the geometries in the geojson layer. Doc for `didTapOverLay()`: [https://developers.google.com/maps/documentation/ios-sdk/reference/protocol_g_m_s_map_view_delegate-p#a3a2bf2ff4481528f931183cb364c0f4b](https://developers.google.com/maps/documentation/ios-sdk/reference/protocol_g_m_s_map_view_delegate-p#a3a2bf2ff4481528f931183cb364c0f4b)

### PR DESCRIPTION
**Pull request by rxng8**
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (not necessary)

Fixes #375 🦕

I have tried and tested the tappable geometry rendered.

### CODE REVIEW

**Comment by arriolac** [comment]
Thanks for the PR. Can you update this so that all geometries and not just polygons and polylines are tappable?

**Comment by rxng8** [comment]
@arriolac Hi, I have added them! Thanks

**Comment by arriolac** [comment]
Thanks, @rxng8. One last edit before we can merge your change—please fix the failing Semantic Pull Request check. You can prefix your PR and commit message with "feat: " which should pass the check.

**Comment by rxng8** [comment]
@arriolac Done! Thanks!

**Pull request merged**
