### PR TITLE
feat: Add GMSMarker subclass allowance on cluster renderer

### LINKED ISSUE #505: IconView does not appear when a subclassed GMSMarker is added to GMUClusterManager.
When we want to use Custom Marker with custom iconView can not see iconView on map.I have opened a PR to fix it.

#### Visual
before-fix

Map should look like this

after-fix

#### Steps to reproduce

  1. Create a new custom class which inherits from GMSMarker
  2. Set custom iconView on it
  4. Create a GMUClusterManager
  5. Add a default GMUDefaultClusterRenderer for clusterManager
  6. Add custom markers to clusterManager
  7. Cluster the markers and you wont see the iconView for not clustered markers

#### Code example

```
class AnnotationView: GMSMarker {}

final class MapMarkerView: UIView {
    private let cornerRadius: CGFloat = 6
    private let triangleHeight: CGFloat = 6
    private let triangleWidth: CGFloat = 12
    private let strokeWidth: CGFloat = 1.0

    private var markerShapeLayer: CAShapeLayer?
    
    private lazy var titleLabel = makeTitleLabel()
    
    init(model: title) {
        self.model = model
        super.init(frame: .zero)
        setupUI()
        titleLabel.text = model
    }
    
    required init?(coder: NSCoder) { fatalError("init(coder:) has not been implemented") }
    
    override func draw(_ rect: CGRect) {
        super.draw(rect)

        let path = UIBezierPath()
        path.move(to: CGPoint(x: cornerRadius, y: 0))
        
  
        path.addLine(to: CGPoint(x: rect.width - cornerRadius, y: 0))
        path.addArc(withCenter: CGPoint(x: rect.width - cornerRadius, y: cornerRadius),
                    radius: cornerRadius,
                    startAngle: CGFloat.pi * 1.5,
                    endAngle: 0,
                    clockwise: true)
       
        path.addLine(to: CGPoint(x: rect.width, y: rect.height - triangleHeight - cornerRadius))
        path.addArc(withCenter: CGPoint(x: rect.width - cornerRadius, y: rect.height - triangleHeight - cornerRadius),
                    radius: cornerRadius,
                    startAngle: 0,
                    endAngle: CGFloat.pi / 2,
                    clockwise: true)
       
        path.addLine(to: CGPoint(x: rect.midX + triangleWidth / 2, y: rect.height - triangleHeight))
        path.addLine(to: CGPoint(x: rect.midX + (triangleWidth / 2) - 2, y: rect.height - 6))
        
        
        path.addCurve(to: CGPoint(x: rect.midX - (triangleWidth / 2) + 2, y: rect.height - 6),
                      controlPoint1: CGPoint(x: rect.midX, y: rect.height),
                      controlPoint2: CGPoint(x: rect.midX, y: rect.height))
    
        
        path.addLine(to: CGPoint(x: rect.midX - triangleWidth / 2, y: rect.height - triangleHeight))
        path.addLine(to: CGPoint(x: cornerRadius, y: rect.height - triangleHeight))
        
        path.addArc(withCenter: CGPoint(x: cornerRadius, y: rect.height - triangleHeight - cornerRadius),
                    radius: cornerRadius,
                    startAngle: CGFloat.pi / 2,
                    endAngle: CGFloat.pi,
                    clockwise: true)
        
        path.addLine(to: CGPoint(x: 0, y: cornerRadius))
        path.addArc(withCenter: CGPoint(x: cornerRadius, y: cornerRadius),
                    radius: cornerRadius,
                    startAngle: CGFloat.pi,
                    endAngle: CGFloat.pi * 1.5,
                    clockwise: true)
        
        path.close()
        
        let shapeLayer = CAShapeLayer()
        shapeLayer.path = path.cgPath
        shapeLayer.fillColor = (UIColor.white1).cgColor

        shapeLayer.shadowColor = UIColor.black.cgColor
        shapeLayer.shadowOpacity = 0.3
        shapeLayer.shadowOffset = CGSize(width: 0, height: 3)
        shapeLayer.shadowRadius = 4
        layer.insertSublayer(shapeLayer, at: 0)
        markerShapeLayer = shapeLayer
    }
    
    func deselect() {
        markerShapeLayer?.fillColor = (UIColor.white1).cgColor
        titleLabel.textColor = .gray700
    }
    
    
    func select() -> ADSProduct {
        markerShapeLayer?.fillColor = (UIColor.indigo1).cgColor
        titleLabel.textColor = .white
        return model
    }
}

private extension MapMarkerView {
    func setupUI() {
        // required to set false for rendering accurate on mapView
        translatesAutoresizingMaskIntoConstraints = false
        
        backgroundColor = .clear
        addSubview(titleLabel)
        
        titleLabel.snp.makeConstraints { make in
            make.top.equalToSuperview().inset(4)
            make.bottom.equalToSuperview().inset(11)
            make.leading.equalToSuperview().inset(6)
            make.trailing.equalToSuperview().inset(6)
        }
    }
    
    func makeTitleLabel() -> UILabel {
        let label = UILabel()
        label.font = .semiBold(style: .xs)
        label.textColor = .gray700
        label.textAlignment = .center
        return label
    }
}

import Foundation
import GoogleMapsUtils

final class GoogleMapsClusterRepository: NSObject {
    private let manager: GMUClusterManager
    private var renderer: GMUDefaultClusterRenderer!
    
    init(mapView: GMSMapView, clusterDistancePoints: UInt = 20, minClusterSize: UInt = 2) {
        let iconGenerator = GMUDefaultClusterIconGenerator()
        let algorithm = GMUNonHierarchicalDistanceBasedAlgorithm(clusterDistancePoints: clusterDistancePoints)!
        renderer = GMUDefaultClusterRenderer(mapView: mapView, clusterIconGenerator: iconGenerator)
        renderer.minimumClusterSize = minClusterSize
        manager = GMUClusterManager(map: mapView, algorithm: algorithm, renderer: renderer)
        super.init()
        mapView.removeObserver(manager, forKeyPath: "camera")
        renderer.delegate = self
        manager.setDelegate(self, mapDelegate: mapView.delegate)
    }
    
    func cluster() {
        manager.cluster()
    }
    
    func clearItems() {
        manager.algorithm.clearItems()
    }
    
    func add(marker: GMUClusterItem) {
        manager.add(marker)
    }
}

extension GoogleMapsClusterRepository: GMUClusterManagerDelegate {
    func renderer(_ renderer: any GMUClusterRenderer, willRenderMarker marker: GMSMarker) {
        if let cluster = marker.userData as? GMUStaticCluster {
            let clusterView = LocationMarkerClusterView(title: "\(cluster.count)")
            clusterView.translatesAutoresizingMaskIntoConstraints = false
            marker.iconView = clusterView
            marker.appearAnimation = .pop
        }
    }
}


extension GoogleMapsClusterRepository: GMUClusterRendererDelegate {
    func clusterManager(_ clusterManager: GMUClusterManager, didTap cluster: any GMUCluster) -> Bool {
        var products: [ADSProduct] = []
        for item in cluster.items {
            if let product = ((item as? GMSMarker)?.iconView as? MapMarkerView)?.model {
                products.append(product)
            }
        }
        print(products)
        return true
    }
}

// Final method to see the result
func cluster() {
  let clusterRepository = GoogleMapsClusterRepository(mapView: mapView)
  let customMarkerView = MapMarkerView(title:"$1.200.000")
  let marker = AnnotationView()
  marker.iconView = customMarkerView
  marker.position = coordinate
  marker.appearAnimation = .pop
  marker.zIndex = Int32(index + 1)
  clusterRepository.add(marker: marker)
  clusterRepository.cluster()
}

```

### PR DESCRIPTION
**Pull request by talipboke**
When 
If can not subclass GMSMarker with custom iconView can not see iconView on Map

Thank you for opening a Pull Request!

---

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [X] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [X] Appropriate docs were updated (if necessary)

Fixes #505  🦕

### CODE REVIEW

**Review by wangela — APPROVED** [review]
Thank you for this contribution!

**Review by iHackSubhodip — APPROVED** [review]
LGTM 🚀

**Comment by wangela** [comment]
@iHackSubhodip As we have reviewed in your Swift translation branch, this change only applies to Objective-C and is not needed in the Swift version of the class.

**Comment by talipboke** [comment]
I have closed the issue :)

**Comment by talipboke** [comment]
@wangela How does the merge process work? Do I need to do anything else?

**Pull request merged**
